### ISSUE TITLE
He can't obf 

### ISSUE THREAD

**Issue by Tarkan-Zarrouk** [EBSmash/HockeyWare-Leak#1]
He was struggling with obfuscating his client with Proguard KEK

![image](https://user-images.githubusercontent.com/83801755/181847613-b49f0e96-42a3-4c23-85ff-b40086e00ce4.png)
![image](https://user-images.githubusercontent.com/83801755/181847643-82f524a4-651b-492b-8d72-dc252b9a5a77.png)
he also used superblaubeere obf kekw

**Comment by EBSmash** [comment]
lmao
